# Generated by Django 5.0.7 on 2024-08-06 08:28

import KingsWayApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KingsWayApp", "0002_donation_subscription_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[KingsWayApp.models.validate_name],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("payment_option", models.CharField(max_length=50)),
            ],
        ),
    ]
