# Generated by Django 5.0.7 on 2024-08-07 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KingsWayApp", "0003_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_option",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("MM", "Mobile Money")],
                max_length=3,
            ),
        ),
    ]
